### PR TITLE
Main Window Bug Fixes

### PR DESCRIPTION
**Pull request by ahalgh**

### CODE REVIEW

**Comment by Kvieta1990** [comment]
Hi @marshallmcdonnell 

We both have tested the new implementation to make sure that all fixes are in place and ADDIE is behaving as expected. Here is a bit summary about what @ahalgh has done,

1. Make the search box in the main Mantid interface working.

2. Change the `Cheat Sheet` link to a temporary website - NOMAD webpage.

3. Fix the issue with chemical formula input - previously only chemical formula created by clicking on periodic table will be accepted and any manual input (even the format is correct) will be rejected. Now this issue is fixed.

4. Make the refresh button working in the reduction configuration window.

5. Change the default value of Q- and r- space parameters in the reduction configuration window.

I will check whether any of these implementations covers what we already have in the GitHub issue list. It will be very nice of you @marshallmcdonnell if you can help reviewing and merging the codes. Thank you so much!

**Comment by Kvieta1990** [comment]
@marshallmcdonnell FYI - checking through issue list in GitHub and found no one relevant to current PR. Thank you!

**Comment by marshallmcdonnell** [comment]
LGTM! :+1:

**Review by marshallmcdonnell — APPROVED** [review]
LGTM! :+1:

**Pull request merged**
