### PR TITLE
Debugging Rietveld and Oncat Functionality

### PR DESCRIPTION
**Pull request by ahalgh**

### CODE REVIEW

**Review by marshallmcdonnell — APPROVED** [review]
So all of this looks great, thank you!

I did see that the CI is failing on testing.
```
ERROR: PyQt < 5.11 is not supported by pytest-qt, use 5.11+ instead.
```

Yet, this is what I would say an "unfixable" problem right now.
_Why unfixable?_
The upstream Mantid Workbench has still not been able to generate a new conda package for us to use (this is where the Qt + PyQt is defined).
The conda recipe was in a "broken" state the last time I was looking at this and seems like little progress has been made (recipe location: https://github.com/mantidproject/conda-recipes/)

I do know that there have been updates to the Mantid Framework conda package to get it back and working (used for mantid-total-scattering)
Maybe using these we can get the Workbench back to working as well.
And Mantid project is suppose to be working on making conda packages "first class citizens" for its distribution so it will probably be fixed eventually for us.

I am okay to merge these in and get them deployed to the DEV environment on analysis cluster for our QA testing and for-go these unit tests issues right now in CI.

**Comment by marshallmcdonnell** [comment]
Submitted [this Issue](https://github.com/neutrons/addie/issues/336) to track the error we see for PyQt

**Comment by marshallmcdonnell** [comment]
@Kvieta1990 (and @ahalgh)
One thing, I know this PR will probably fix a lot of issues.
Is there any chance one of you would mind to go through and update (or close out) issues that are addressed in this PR?

**Comment by ahalgh** [comment]
Yeah sure!

**Comment by Kvieta1990** [comment]
@marshallmcdonnell Sorry Marshall, I won't have time today to check through the issues, but I think @ahalgh will do that tomorrow.

Thanks a lot for reviewing and commenting on the CI failing issue. Not sure I am understanding it properly since I am working on something now which occupies my mind. But I will definitely give it a look tonight and see if I can digest it. Thank you!

**Comment by marshallmcdonnell** [comment]
@Kvieta1990 
No worries, and not today, just "some time"
And yeah, @ahalgh, if you can go through, that would be great!

Also, our deployment pipeline will fail at thet "test" phase if I try to deploy via a release to conda.
The current deployment to analysis requires a conda package release.
But, I might try to refactor the same way that @earnestdl did for mantid-total-scattering so we can deploy our "dev" branch directly to analysis.

**Comment by Kvieta1990** [comment]
> @Kvieta1990 (and @ahalgh)
> One thing, I know this PR will probably fix a lot of issues.
> Is there any chance one of you would mind to go through and update (or close out) issues that are addressed in this PR?

@marshallmcdonnell @ahalgh  I went through the issues in the list and did close several issues that we just fixed with PR [GitHub issue/pull request detail](https://github.com/neutrons/addie/issues/335) that we just submitted.

**Comment by marshallmcdonnell** [comment]
Thanks to you both, much appreciated!
I just looked over all of them, great work!

**Pull request merged**
