### PR TITLE
Add in Fourier filter capability

### PR DESCRIPTION
**Pull request by Kvieta1990**
The Fourier filter capability is added to ADDIE interface through underlying `pystog` module. Conda recipe needs to be updated accordingly to add in the dependency upon `pystog`.

I will be waiting for @marshallmcdonnell to sort out the `pystog` conda package issue.

### CODE REVIEW

**Review by marshallmcdonnell — COMMENTED** [review]
Overall, looks good! Thanks for adding the error handling as well!

I need to launch the GUI and try it out still.
I don't readily see from the code how the Fourier Filter is accessed from the GUI just looking at the code.

**Comment by marshallmcdonnell** [comment]
This PR addresses Issue #91

**Comment by marshallmcdonnell** [comment]
@Kvieta1990  I realize CI is not kicking off for your pull request.
We need to get PR #319 merged to `master` and then have you merge (or rebase) off of `master` to pull that change into your PR.

Sorry, overlooked that step.

**Comment by Kvieta1990** [comment]
> @Kvieta1990 I realize CI is not kicking off for your pull request.
> We need to get PR #319 merged to `master` and then have you merge (or rebase) off of `master` to pull that change into your PR.
> 
> Sorry, overlooked that step.

I have merged #319.

**Comment by marshallmcdonnell** [comment]
Great, thanks!
If you don't mind, can you merge or rebase off master now and let's see if that fixes the CI trigger.
I am still working on PyStoG.

**Comment by Kvieta1990** [comment]
> Overall, looks good! Thanks for adding the error handling as well!
> 
> I need to launch the GUI and try it out still.
> I don't readily see from the code how the Fourier Filter is accessed from the GUI just looking at the code.

The Fourier filter is only working for real space PDF but not reflected in the Q-space data. Not sure whether we do want the filter applied onto Q-space output as well. May need to discuss with Matt about this and I will put it in if needed.

**Comment by Kvieta1990** [comment]
Sorry, not sure how to do that. When I tried to pull from my terminal, it says `Already up to date.`

**Comment by marshallmcdonnell** [comment]
Will take discussion offline (in Slack)

**Pull request closed without merging**
