### PR TITLE
add in Fourier filter capability

### PR DESCRIPTION
**Pull request by Kvieta1990**
The Fourier filter capability is added to ADDIE interface through underlying `pystog` module. Conda recipe needs to be updated accordingly to add in the dependency upon `pystog`.

I will be waiting for @marshallmcdonnell to sort out the `pystog` conda package issue.

Also, current implementation only applies Fourier filter in real-space. Need to discuss with Matt whether we want the Fourier filter to be reflected in Q-space as well. Will put in corresponding implementation if needed.

Related to issue #91

### CODE REVIEW

**Comment by marshallmcdonnell** [comment]
Okay, looking at this further (since I am finishing up the PyStoG stuff), I am seeing stuff I didn't realize before:

1. The fourier filter is being applied to all PDF functions. I think it should be optional. The User should be able to control this via the GUI (see Issue #91 for the original idea)

2. The filter is being carried out to the minimum R (`Rmin` box) that is specified in the GUI. Yet, this is meant to control the integration limit. Maybe it is okay to "piggyback" off this value but they serve two different purposes. I think this should be discussed further. Why? You want to possibly not apply a fourier filter but change the limit of integration.

3. Related to the following comment:
> Also, current implementation only applies Fourier filter in real-space. Need to discuss with Matt whether we want the Fourier filter to be reflected in Q-space as well. Will put in corresponding implementation if needed.

I think we should give the Q-space function as well (not over-write the original but provide the new one) since you want to provide reciprocal space function that gave you the real space function via the fourier transform. Will need this for analysis in programs that can fit the pair (like RMCProfile). Right now, the User will be left with a reciprocal space function that does not have the filter applied and the real space function that does have this applied, thus not an equal pair.

**Comment by marshallmcdonnell** [comment]
And now that I review Issue #91, honestly, I think the first step should be just to add a back transform from real space to reciprocal space [i.e. G(r) -> S(Q)].

From that, you can actually perform the fourier filter yourself in the GUI. Yet, I do want to include your feature addition of a "quick" fourier filter button / setup to the GUI

**Review by marshallmcdonnell — CHANGES_REQUESTED** [review]
Overall, I think we need to discuss more (see above comments).

Big points are:
The fourier filter needs to be optional and controlled via the GUI.
We probably should solve issue #91 first as a "first step".
The current implementation would give the User the incorrect real space, reciprocal space pair of functions [an S(Q) that the G(r) did not come from]

**Comment by marshallmcdonnell** [comment]
*Update:*
Putting issue #91 in backlog.
From offline discussion with @Kvieta1990 and Matt Tucker, that feature is not important.

Changes that still need to happen:
- [ ] The fourier filter needs to be optional and controlled via the GUI.
- [ ] Include the plot of the fourier filtered S(Q) and G(r) if we do apply the fourier filter

**Comment by Kvieta1990** [comment]
Will close this PR and create a new one, putting in stuff based on our latest discussion as summarized by @marshallmcdonnell below,

> _Update:_
> Putting issue #91 in backlog.
> From offline discussion with @Kvieta1990 and Matt Tucker, that feature is not important.
> 
> Changes that still need to happen:
> 
> * [ ]  The fourier filter needs to be optional and controlled via the GUI.
> * [ ]  Include the plot of the fourier filtered S(Q) and G(r) if we do apply the fourier filter

**Pull request closed without merging**
